# Generated by Django 4.0.4 on 2022-04-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('age', models.IntegerField(verbose_name='age')),
                ('salary', models.DecimalField(decimal_places=10, max_digits=100000000000, verbose_name='salary')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('number', models.IntegerField(verbose_name='number')),
                ('country', models.CharField(max_length=255, verbose_name='country')),
                ('sex', models.BooleanField(verbose_name='sex')),
            ],
        ),
    ]
