# Generated by Django 4.0.4 on 2022-04-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='name',
            field=models.TextField(max_length=255, verbose_name='name'),
        ),
    ]
