# Generated by Django 4.0.4 on 2022-04-20 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_emp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='name',
            field=models.TextField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='name'),
        ),
    ]
