# Generated by Django 4.0.4 on 2022-04-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_emp_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='country',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='email',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='number',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='sex',
        ),
    ]
