# Generated by Django 4.0.2 on 2022-04-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_emp_country_remove_emp_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='name',
            field=models.TextField(max_length=255, verbose_name='55'),
        ),
    ]
