# Generated by Django 4.0.2 on 2022-04-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_emp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='name',
            field=models.TextField(max_length=255, verbose_name='name'),
        ),
    ]
